version: '3.5'
services:
  fastapi_5:
    build: .
    container_name: fastapi_5
    restart: always
    ports:
      - ${APP_PORT}:${APP_PORT}
    volumes:
      - .:/src
      - ./logs:/src/logs
    env_file:
      - .env
    command: uvicorn main:app --reload --host 0.0.0.0 --port ${APP_PORT}

  elastic_5:
    image: elasticsearch:8.10.2
    container_name: elastic_5
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms200m -Xmx200m"
    restart: always
    volumes:
      - elastic_5:/usr/share/elasticsearch/data
    ports:
      - 9200:9200


volumes:
  elastic_5:
